### ISSUE TITLE
Non-Interactive Use

### ISSUE THREAD

**Issue by aminemarref** [fricas/fricas#15]
Hello,

How would one use FriCAS non-interactively from a terminal? I would like to be able to pass input (e.g. to integrate a function) to FriCAS from some text file, and save output (result of integration) to some text file -- as a way of batch solving stuff?

Thanks.

**Comment by hemmecke** [comment]
> How would one use FriCAS non-interactively from a terminal? I would
> like to be able to pass input (e.g. to integrate a function) to
> FriCAS from some text file, and save output (result of integration)
> to some text file -- as a way of batch solving stuff?
There are serveral methods. I do something like this when generating the
output for the content in book.pdf (http://fricas.github.io/book.pdf).

That is, however a bit more complicated. Let me first tell you the
simplest form.

  echo "integrate(x^2, x)" | fricas -nosman

Where you pipe the output to is your problem.

But you might ask how to figure out where the output starts and ends and
there might be the wish whether you like to see the input command also
in the output. I do this with the help of an ioHook facility. But before
I continue, let me ask you about your clear specification.

Ralf

**Comment by aminemarref** [comment]
Thanks a lot for the prompt answer :-) Yes, I would like to know the way by which I can obtain the "pure" output. 

Also, is there a way to avoid pretty-printing expressions? So for example, I get (1/3)*x^3 (or any easily-parsable single-line format) in the previous example instead of the syntactically-sugared multi-line expression?

**Comment by hemmecke** [comment]
> Also, is there a way to avoid pretty-printing expressions?

Not so easy to answer.

Some people would say that "::InputForm" does the job.

(1) -> integrate(x, x)::InputForm

   (1)  (* (/ 1 2) (^ x 2))
                                                Type: InputForm

I didn't like this and also wanted to have oneline output.
So I wrote Format1D. You find it in the commit "FormattingFramework" in
the file fmt1d.spad.

https://github.com/hemmecke/fricas/commit/bc6011d1540da905c9e1630174d0ef75d64a92cf

That hasen't yet made it into FriCAS, but hopefully becomes available in
the next release.

Of course you can clone my FriCAS repo and switch to the "formatted"
branch and compile it. Then you would have the following available:


(1) -> wrapProEpi(t, F) ==>   setDefault!(  (s: String): OutputBox +->
vconcat([box concat("--FORMAT:BEG:", t),
defaultPrologue(s)$F],1,-1)$OutputBox,  (s: String): OutputBox +->
vconcat([defaultEpilogue(s)$F, box concat("--FORMAT:END:",
t)],1,-1)$OutputBox  )$Formatter(F);
                                                       Type: Void
(2) -> wrapProEpi("Format1D", Format1D);

    Type: Record(prolog: (String -> OutputBox),epilog: (String ->
OutputBox))
(3) -> formatters := [Formatter Format1D] pretend
List(OutputFormatterCategory);

                               Type: List(OutputFormatterCategory)
(4) -> setFormats!(formatters)$FormattedOutput;
                                                       Type: Void
(5) -> )set output algebra off
(5) -> )set output formatted on
(5) -> integrate(x^2, x)

--FORMAT:BEG:Format1D
1/3*x^3
--FORMAT:END:Format1D

                              Type: Polynomial(Fraction(Integer))

It looks a bit involved, but it is not clear yet, how it actually will
appear in FriCAS. Probably, this way, because, although working nicely,
it should be considered experimental (as it is new).

As you see from the code above, you can control, what comes before and
after the actual expression.

Now a word of warning. Format1D is certainly not perfect, but please
report back if you find something that doesn't satisfy your wishes. It
is customizable, even without recompiling FriCAS. But I will wait for
the bug reports.

There is another way with ioHooks, but Format1D is at the moment only
available in my repository and as you see from above ioHooks are not
needed here.

Hope that helps.

Ralf

**Comment by hemmecke** [comment]
Oooops. I replied via e-mail, so my output doesn't look so nice. Maybe you subscribe to the official mailing list. Currently, most discussion still happens there.
https://groups.google.com/forum/#!forum/fricas-devel
