### ISSUE TITLE
Evaluation/substitution in matrices fails

### ISSUE THREAD

**Issue by lucag73** [fricas/fricas#172]
If I define a matrix with more than one entry in a Fraction(Polynomial(Integer)), then eval (to substitute the entry itself) fails.
Also the expected type of eval(A,x=1) should be Matrix(Fraction(Polynomial(Integer))) and not just Fraction(Polynomial(Integer)))

Is this behavior expected (or am I missing something on the expected semantics of eval/subst)?

With  best regards,
 luca

Here there is a minimal transcript:

(1) -> A:=matrix([[1/x]])

        +1+
   (1)  |-|
        +x+
                                  Type: Matrix(Fraction(Polynomial(Integer)))

(2) -> B:=matrix([[1/x,x]])

        +1   +
   (2)  |-  x|
        +x   +
                                  Type: Matrix(Fraction(Polynomial(Integer)))
(3) -> eval(A,x=1)

   (3)  1
                                          Type: Fraction(Polynomial(Integer))
(4) -> eval(B,x=1)
   There are 10 exposed and 6 unexposed library operations named eval 
      having 2 argument(s) but none was determined to be applicable. 
      Use HyperDoc Browse, or issue
                              )display op eval
      to learn more about the available operations. Perhaps 
      package-calling the operation or using coercions on the arguments
      will allow you to apply the operation.
 
   Cannot find a definition or applicable library operation named eval 
      with argument type(s) 
                    Matrix(Fraction(Polynomial(Integer)))
                        Equation(Polynomial(Integer))
      
      Perhaps you should use "@" to indicate the required return type, 
      or "$" to specify which version of the function you need.

**Comment by oldk1331** [comment]
Hi, firstly, from `)show Matrix FRAC POLY INT`, you can see there is no `eval` function in this domain.

Then, by `)set message bottom on` to show how interpreter selects the function, for `eval(A,x=1)`, there's:

````
 Function Selection for eval
      Arguments: (FRAC(POLY(INT)), EQ(POLY(INT))) 
      Target type: SQMATRIX(1,FRAC(POLY(INT))) 
 
 [1]  signature:   (FRAC(POLY(INT)), EQ(POLY(INT))) -> FRAC(POLY(INT))
      implemented: slot   (Equation (Polynomial (Integer))) from FRAC(POLY(INT))
````

So the interpreter coerces `A` to type `FRAC(POLY(INT))` first, then do the eval in that domain.

So for B, it can't be coerced to that domain, thus no proper "eval" can be selected.

**Comment by oldk1331** [comment]
You can use "eval" inside "map" to do the evaluation/substitution:

````
(2) -> map(y+->eval(y,x=2),B)

        +1   +
   (2)  |-  2|
        +2   +
````

**Comment by lucag73** [comment]
Thanks, that works nicely and it is indeed much more elegant than manually iterating on all entries of the matrix.

I am still curious about why this happens (and if it is supposed to happen).
A simpler example than the one before is with lists (of course everything is fine if I use the syntax you proposed).

eval([1,x],x=1) works; 
eval([x,x],x=1) does not work;
eval([1,x,x],x=1) works;
eval([x,x,x],x=1) does not work.

It is curious.

**Comment by lucag73** [comment]
I understand; actually with lists it is very evident what the difference between say [1,x] and [x,x] is and why they behave differently.
What I missed is that I silently assumed eval to act on lists (and matrices as well) either with the proper method (where defined)
or recursively on the objects therein contained (as with the map example).

So I expected eval(A,x=1) to evaluate on an entry-by-entry basis (with the proper type and suitable delegations).
If A is a Matrix POLY INT, then it works if A is a Matrix FRAC POLY INT it does not.

**Comment by hemmecke** [comment]
> If A is a Matrix POLY INT, then it works if A is a Matrix FRAC POLY INT it does not.

Yes. The problem is "Fraction". Well, not really a problem, but Fraction 
is a generic constructor of a quotient field.

If you look at the sources

https://github.com/fricas/fricas/blob/master/src/algebra/fraction.spad#L263

then Fraction(S) exports QuotientFieldCategory(S)

https://github.com/fricas/fricas/blob/master/src/algebra/fraction.spad#L91

and that means it exports also FullyEvalableOver(S).

https://github.com/fricas/fricas/blob/master/src/algebra/equation1.spad#L292

That in turn export Evalable(S)

https://github.com/fricas/fricas/blob/master/src/algebra/equation1.spad#L296

under the condition that S is of type Evalable(S).

Long story short. Put S=Polynomia(Integer) and you find that
Fraction(Polynomial(Integer)) exports Evalable(Polynomial(Integer)).
```
%%% (489) -> Fraction(Polynomial Integer) has Evalable(Polynomial(Integer))

    (489)  true
                                               Type: Boolean

%%% (490) -> Fraction(Polynomial Integer) has 
Evalable(Fraction(Polynomial(Integer)))

    (490)  false
                                               Type: Boolean
```
However, what you actually need, that (490) would return true.
Then eval on the Matrix would work.

But think about what "true" actually means.
For Polynomials we have
https://github.com/fricas/fricas/blob/master/src/algebra/polycat.spad#L401, 
i.e. we basically replace a variable by the respective substitution 
polynomial.

For Fraction(S) you have the problem that it is a generic constructor. 
There is no concept of a variable. (Or can you imagine the variable in 
Fraction(Integer).

A solution would be to implement a package that provides
an eval function.
```
eval: (Fraction Polynomial Integer, Equation Fraction Polynomial 
Integer) -> Fraction Polynomial Integer
```
But that obviously does still not give 
Evalable(Fraction(Polynomial(Integer))) so that the Interpreter would be 
able to find and apply this function automatically.
In fact, why should the interpreter pick up a user-programmed eval 
function. The question here is how much time we want the interpreter to 
search for an appropriate function in all of the available function of 
the library. It is already complicated enough with the various coerce, 
convert, and retract functions.

I hope, you get not too frustrated with how FriCAS works. If you stay 
long enough and start library programming, you will love types.
