### ISSUE TITLE
doc: book: Tex command spadtype does not support ->

### ISSUE THREAD

**Issue by nsajko** [fricas/fricas#20]
The Fricas book that lives in src/doc/htex uses the spadtype Tex command for type setting Fricas/Spad types. The problem is that the command does not handle the arrow operator used for defining function types. E.g., check page 827 of section 11.10. of https://fricas.github.io/book.pdf after "package exports the required operation".

**Comment by nsajko** [comment]
The Tex files in which the bug manifests are ug06.htex, ug11.htex and ug12.htex.

**Comment by nsajko** [comment]
Hmmm, maybe instead of doing `\spadtype{A -> B}`, it should be `\spadtype{A} \spadop{->} \spadtype{B}` instead? That seems like it could make more sense?

**Comment by hemmecke** [comment]
Nice that yet another person starts to contribute!!!

On 10/29/20 6:40 AM, Neven Sajko wrote:> Hmmm, maybe instead of doing
`\spadtype{A -> B}`, it should be
> `\spadtype{A} \spadop{->} \spadtype{B}` instead? That seems like it
> could make more sense?
Well that probably would work, but look ugly. I've no time currently,
but if you look into fricas.sty you will find that \spadop will expand
to \textspadop and that the argument will be set in \texttt.

A better alternative is perhaps \spad{->}. But I first must try what
looks better.

**Comment by hebisch** [comment]
On Wed, Oct 28, 2020 at 10:40:14PM -0700, Neven Sajko wrote:
> Hmmm, maybe instead of doing `\spadtype{A -> B}`, it should be `\spadtype{A} \spadop{->} \spadtype{B}` instead? That seems like it could make more sense?

Best solution is to modify \spadtype so that it corretly handles '->'.
Second possibility it to introduce new command like 'spadfuntype'
and restrict all hasking to implementation of 'spadfuntype'.
Using code above inline would be rally bad.

-- 
                              Waldek Hebisch

**Comment by hemmecke** [comment]
\spadfuntype is a good idea, but still not perfect. Now that we have
fricas.github.io/api, I eventually would like to make each \spadtype
into a link to the respective api page. Already \spadtype{Fraction
Integer} is a problem in that respect since I must find a hack to split
at whitespace. Probably doable. Then \spadtype{F A -> B} should show
correctly. I just don't know how to handle \spadtype{F(A)}. That would
be too much hacking for just a few cases.

**Comment by nsajko** [comment]
OK, then; fixing spadtype seems like a good idea, but I don't know enough Latex or Tex to fix it myself. Just a FYI.
