### ISSUE TITLE
doc: book: spadcommand missing OutputForm output

### ISSUE THREAD

**Issue by nsajko** [fricas/fricas#24]
In section 6.19 of the book, above the text `Being purists, we find` there should be a Pascal's triangle which is instead missing.

Taking a look at line 2346 of src/doc/htex/ug06.htex points to a spadcommand Tex command as the likely culprit.

The section shows an example of OutputForm usage, which is related to the problem, I guess.

**Comment by hemmecke** [comment]
Thank you for reporting this issue, since I do not yet know how to handle it, I leave it open for the moment.

If you look into the generated ug06.spool file, the output is actually there, but it is not included in an environment, so spool2tex.awk cannot distinguish it from the actual commands that also do not appear inside any environment (and without the "-- " in the first columns.

That's certainly a bad thing, but it is hard to handle, since actually the command does not produce any result that goes the usual way, but rather outputs directly.

Maybe this is a place where I should hardcode the output into the ug06.htex file.

```
-- \begin{xtc}
-- \begin{xtccomment}
-- Look at the result.
-- \end{xtccomment}
-- \begin{spadsrc}
-- for i in 1..7 repeat displayRow i 
-- \end{spadsrc}
for i in 1..7 repeat displayRow i 
 
-- \begin{MessageOutput}
   Compiling function pascal with type (Integer, Integer) -> 
      PositiveInteger 
-- \end{MessageOutput}
-- \begin{MessageOutput}
   Compiling function pascalRow with type PositiveInteger -> List(
      PositiveInteger) 
-- \end{MessageOutput}
-- \begin{MessageOutput}
   Compiling function displayRow with type PositiveInteger -> Void 
-- \end{MessageOutput}
                                         1
                                        1 1
                                       1 2 1
                                      1 3 3 1
                                     1 4 6 4 1
                                   1 5 10 10 5 1
                                 1 6 15 20 15 6 1
-- \begin{MessageOutput}
                                                                   Type: Void
-- \end{MessageOutput}
-- \end{xtc}
-- Being purists, we find this less than satisfactory.
-- Traditionally, elements of Pascal's triangle are centered between
-- the left and right elements on the line above.
```
