### ISSUE TITLE
Unable to build on MacOSX

### ISSUE THREAD

**Issue by SorinS** [fricas/fricas#38]
MacOSX Catalina - 10.15.4, Darwin Kernel Version 19.4.0, SBCL 2.0.11

(doing (GradedAlgebra R E) ((Category) (CommutativeRing) (AbelianMonoid)))
   Semantic Errors: 
      [1] cannot form Join of: ((GradedModule t#1 t#2) (RetractableTo t#1) (CATEGORY domain (SIGNATURE (One) ($) constant) (SIGNATURE product ($ $ $))))
 
   Warnings: 
      [1]  RetractableTo has no value
 
****** comp fails at level 2 with expression: ******
(|Join| (|GradedModule| |t#1| |t#2|) | << | (|RetractableTo| |t#1|) | >> |
        (CATEGORY |domain| (SIGNATURE 1 ($) |constant|)
         (SIGNATURE |product| ($ $ $))))
****** level 2  ******
$x:= (RetractableTo t#1)
$m:= (Category)
$f:=
((((|t#2| #) (|t#1| #) (E # #) (R # #) ...)))
 
   >> Apparent user error:
   cannot compile (RetractableTo t#1)

**Comment by oldk1331** [comment]
Can confirm this problem: https://github.com/oldk1331/fricas/runs/1895967444

This failure is not directly retread with `GradedAlgebra`, because removing it and it will fail again at ` RetractableTo` later.

On Linux, with sbcl 2.0.11, it builds fine.

I do not have a macos system at hand, so can't investigate further for now.

(FriCAS used to build fine on macos a few years ago.)

You can try to build version 1.3.6 or use git bisect to investigate this problem.

**Comment by oldk1331** [comment]
Okay, the problem is that, you are using in-tree building.

It fails because of macOS uses case-insensitive filesystem.

Use `mkdir build; cd build; ../fricas/configure` and you should be fine.

I was bitten by this problem before (on Windows), we really should add a check for this in `configure`.  I'll do that.

**Comment by oldk1331** [comment]
As you can see in https://github.com/oldk1331/fricas/runs/1960731533

The build succeeds on macOS.

**Comment by dimpase** [comment]
FriCAS 1.3.6 builds and works on macOS just fine, I don't know why this started to be a problem on 1.3.7.
Could you explain, because it's not at all clear how out-of-tree build would magically solve this, if at all.

**Comment by dimpase** [comment]
It could be Lisp compiler dependent, of course - breaks with sbcl, but works with ecl.

**Comment by dimpase** [comment]
with ecl in builds on macOS in-tree just fine (I checked by removing the corresponding test from ./configure and building),
see https://trac.sagemath.org/ticket/32049

**Comment by hebisch** [comment]
On Thu, Jul 08, 2021 at 06:05:32AM -0700, Dima Pasechnik wrote:
> FriCAS 1.3.6 builds and works on macOS just fine, I don't know why this started to be a problem on 1.3.7.
> Could you explain, because it's not at all clear how out-of-tree build would magically solve this, if at all.

In-tree build on case insensitive filesystem was always unsupported.
It could work, but there are many possibilites for weird errors
due to overwritten files.  Up to 1.3.6 FriCAS depended on disclaimer
in documention, but despite disclaimer we were getting reports
of build errors which after investigation were due to in-tree
build on case insensitive filesystem.  So we implemented a check
which triggers error in configure.

BTW: This was discussed and you should be able to find info
in mailing list archives.

-- 
                              Waldek Hebisch

**Comment by dimpase** [comment]
I would like to create an option to override this check. Would you accept a PR that does this?

For the time being we just use a patch that removes the check from ./configure, but this is less than ideal...

**Comment by hebisch** [comment]
On Sun, Jul 11, 2021 at 10:37:18AM -0700, Dima Pasechnik wrote:
> I would like to create an option to override this check. Would you accept a PR that does this?
> 
> For the time being we just use a patch that removes the check from ./configure, but this is less than ideal...

Yes, if you really want this.  Just to add a bit of context: in-tree
build _will_ fail on case-insensitive filesystem when pregenerated
files are absent (say if you use git checkout instead of
release tarball).

-- 
                              Waldek Hebisch

**Comment by dimpase** [comment]
see #61 for the option to override the check
