### ISSUE TITLE
Organize and document "portability functions"

### ISSUE THREAD

**Issue by stylewarning** [fricas/fricas#50]
There are lots of places in the source code where "portability functions" are defined. For instance, in `nlib.lisp`, the function `COPY-LIB-DIRECTORY` is defined for most supported Lisp compilers. I propose that these functions are collected and organized somewhere so that (1) non-portable code is segregated, (2) it's easier to port to a new lisp compiler.

**Comment by oldk1331** [comment]
Hi, on this subject, are you familiar with portable common lisp library that handles file operation?

**Comment by hebisch** [comment]
On Mon, Mar 08, 2021 at 01:11:05AM -0800, Robert Smith wrote:
> There are lots of places in the source code where "portability functions" are defined. For instance, in `nlib.lisp`, the function `COPY-LIB-DIRECTORY` is defined for most supported Lisp compilers. I propose that these functions are collected and organized somewhere so that (1) non-portable code is segregated, (2) it's easier to port to a new lisp compiler.

In a sense almost all our Lisp code is "portability functions".  To
explain structure of code a bit more:
- 'src/lisp' subdirectory contains functions that estabish initial
  environment expected by rest of FriCAS.  More specificaly,
  * fricas-package.lisp i fricas-lisp.lisp establish package
    and basic utilities like build executable, foregin calls,
    system calls
  * primitives.lisp contains constructs which mainly are for
    support of Boot and Spad compilers, more precisely
    compiler output uses this code
  * num-gmp.lisp is interface to GMP
- in 'src/boot' subdirectory we have a single file which is specific
  to needs of Boot compiler
- in 'src/interp' subdirectory we mostly legacy code.  We keep
  old file structure to easier track history: this code is/was
  complicated for various bad reasons and history makes it
  easier to understand.  Those files are bugfix-mostly, new
  things normally do not go there.  Somewhat special is
  'foam_l.lisp', it contains macros and functions used
  by Aldor compiler.  This code is only used by Aldor
  interface, so is is separate file form other Lisp file.
  Logically it is related to Spad runtime support routines
  (written in Boot) which are in 'src/interp'

To put this in different words: current orgarnisation of
source files has it logic.  'src/lisp' is lowest level
layewise, other subdirectories contain subsystems.
It is a judgement call is layering is more important
than containment in common subsystem.  For 'foam_l.lisp'
IMO subsystem view is the right one, this code is
for exclusive use of one subsystem (Aldor interface).
For other it is less clear, but given doubt my
choice was to keep things in the same place (as I
wrote it avoid distracting changes).
  
-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
> Hi, on this subject, are you familiar with portable common lisp library that handles file operation?

Yes. I use UIOP which comes bundled with ASDF, which itself is available on most Lisp implementations by default.

**Comment by stylewarning** [comment]
@hebisch For a sufficiently liberal interpretation of “portability” I agree with you. However, there are definitely two categories of functions present, which are plainly syntactically obvious:

- There’s non-ANSI functionality which is implementation-specific. These are `#+` conditional used.
- There’s ANSI functionality which is used to create or bootstrap Boot or Spad. There are several sub-flavors here, some of which you point out, like having primitive functions for use as compiler output. 
- There’s a mix of ANSI and non-ANSI functionality which serves to set up the Lisp environment by way of installing or mutating aspects of the Lisp image. These don’t belong in library files at all. 

Right now, all of this functionality is haphazardly mixed together. If you asked me to port FriCAS to, say, Mezzano or Allegro, it would take me a day of head scratching to find all these variants strewn around the code.

If instead CL-implementation-specific code were compartmentalized *and documented* (such functions don’t even have expected behavior documented!), porting would be easier, debugging would be easier, maintenance for specific implementations would be easier, etc. 

(To be clear, I don’t propose upending the current logic of the directory layout.)

**Comment by hebisch** [comment]
On Tue, Mar 09, 2021 at 01:31:57PM -0800, Robert Smith wrote:
> @hebisch For a sufficiently liberal interpretation of ???portability??? I agree with you. However, there are definitely two categories of functions present, which are plainly syntactically obvious:
> 
> - There???s non-ANSI functionality which is implementation-specific. These are `#+` conditional used.
> - There???s ANSI functionality which is used to create or bootstrap Boot or Spad. There are several sub-flavors here, some of which you point out, like having primitive functions for use as compiler output. 
> - There???s a mix of ANSI and non-ANSI functionality which serves to set up the Lisp environment by way of installing or mutating aspects of the Lisp image. These don???t belong in library files at all. 

Well, final FriCAS image is an optimization, that performs partial
initialization and preloads some code.  It is natural to share
code for final image with code for image used during build.
There are other aspects that make it natural to put this code
togther in 'src/interp' subdirectory.  Compared to Axiom,
FriCAS moved parts that were reasonably independent from
other 'src/interp' code to 'src/lisp' (one benefit is that
Boot compiler can also use machinery from 'src/lisp', but
can not use anything from 'src/interp').

> Right now, all of this functionality is haphazardly mixed together. If you asked me to port FriCAS to, say, Mezzano or Allegro, it would take me a day of head scratching to find all these variants strewn around the code.

If you want to do port in a day you are probably too optimistic.
Having said that, there are two ports done by developers who
do not take part in normal FriCAS developement, so this can not
be very hard.  And there are simple tactic to get started:
- differential analysis: look what was done in commits adding
  past ports (we have resonably clean history in SCM)
- grep for conditionals corresponding to various implementations,
  new implementation is likely to need entry there, and that
  should cover most of the port.
> If instead CL-implementation-specific code were compartmentalized *and documented* (such functions don???t even have expected behavior documented!), porting would be easier, debugging would be easier, maintenance for specific implementations would be easier, etc. 
> 
> (To be clear, I don???t propose upending the current logic of the directory layout.)

I do not understand that is asked (proposed???) there.  Current
code has its constraints and its logic.  I do not say that
this logic is perfect, but seem to be mostly right.  So I expect
that potential fixes will concrete and localized.  And even
a small proposal for fix needs some discussion, namely to make
sure that it satisfies known constraints and fits well into
existing structure.

A litte extra remark: one easy way to create chaos is to
have two different persons trying to impose different orders.
FriCAS has its own share of such problems due to long
developement history and transitions between maintainers.
But if you want to be part of solution (and not part of
problem) you need to spend some effort to understand why
code is organized in current way.  It is good to ask
if some aspect bothers you.

Concerning documentation, this is big meta-issue, too
big to write about in this message.  
-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
So far, I haven't heard very much convincing rationale from any maintainer as to why the Common Lisp code is as messy and unidiomatic as it is. It is, by and large, sloppy, difficult to read, and doesn't play well with any existing Common Lisp tooling, difficult to debug, etc. Somebody who finishes reading a textbook like _Practical Common Lisp_ or _Paradigms of AI Programming_ might feel equipped to be a contributor to FriCAS, but then they'll be in for a surprise when they find how goofy and difficult it is to read, for no actually logical reason except for vague appeals to preferred style (e.g., "we like the  Lisp code to look like Boot/Spad code"). What I speculate is the case is that there's no deeply logical reason for the code being the way it is, except that the maintainers are very cognizant of the current structure of the code, and non-trivial changes to the code would be disruptive to the maintainers' mental model and understanding, which would in turn disrupt their ability to maintain.

Your suggestions to do "differential analysis via git commits" is a testament to the barely tenable nature of the current code; instead of making the code self-evident as to what is implementation-specific or not, we instead have to sift through over 2,000 commits of history to find what people did before if we have any desire to run FriCAS on any of the many extant Lisps (e.g., Allegro, Mezzano, Clasp, SICL, and mocl).

To be clear, I wholly respect the way the maintainers wish to maintain FriCAS. The maintainers have put in over a decade of effort in keeping this code working, and I'm a newbie who has spent maybe a grand total of one month working with FriCAS source code over the past 10 years. If the FriCAS maintainers tell me, "look, we prefer to make extremely conservative changes because the code is in a working state and our philosophy is to fix bugs and add math functionality," then I'd be OK with that. And, while my PRs have only been up for but a couple days, that is the clear message I am getting. This is my problem for misunderstanding FriCAS's goals as a project (e.g., to make FriCAS [nee Axiom] easier to develop, more efficient, etc.).

I can, at my leisure, always work on a personal copy of FriCAS to make the kinds of changes I feel prudent for improving FriCAS and its ease of use. As a patron of open-source software, however, I wish to put in effort in making my changes available upstream (i.e., to you) so that we don't further contribute to the endless forks of this gargantuan system. I'm trying to offer help as both a user of FriCAS, an interested developer of FriCAS, a professional Common Lisp programmer, and a manager of a team of Common Lisp programmers.

**Comment by oldk1331** [comment]
> So far, I haven't heard very much convincing rationale from any maintainer as to why the Common Lisp code is as messy and unidiomatic as it is. It is, by and large, sloppy, difficult to read, and doesn't play well with any existing Common Lisp tooling, difficult to debug, etc.

Probably because the Lisp code was written 50 years ago, before the birth of Common Lisp.

Another reason might be that, FriCAS is not built in Lisp, but in SPAD which is on Lisp.  Lisp lacks the various type features so the original Scratchpad developers chose to invent a new language for this CAS.

Currently SPAD is compiled to Common Lisp, but if SPAD compiler is rewritten in SPAD and has code generator other than Lisp, then Lisp will not be essential.

If you look through the mailing list, you will find many many of my patches are shot down.  I suggest you to make small atomic patches first, and make bigger structural changes when you are more familiar with the code.

**Comment by hebisch** [comment]
On Wed, Mar 10, 2021 at 12:18:53AM -0800, Robert Smith wrote:
> 
> Your suggestions to do "differential analysis via git commits" is a testament to the barely tenable nature of the current code; instead of making the code self-evident as to what is implementation-specific or not, we instead have to sift through over 2,000 commits of history to find what people did before if we have any desire to run FriCAS on any of the many extant Lisps (e.g., Allegro, Mezzano, Clasp, SICL, and mocl).

I already gave you important hint, namely Lispworks.  I case you
are really interested simple search trough ChangeLog gives you
the followning (which is the right commit):

2010-01-08  Rainer Joswig ***@***.***>

        * configure.ac, config.lisp, src/scripts/document.in,
        src/interp/nlib.lisp, src/interp/util.lisp,
        src/interp/macros.lisp, src/interp/vmlisp.lisp,
        src/lisp/Makefile.in, src/lisp/fricas-lisp.lisp:
        Support build with Lispworks.

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Wed, Mar 10, 2021 at 12:18:53AM -0800, Robert Smith wrote:
> So far, I haven't heard very much convincing rationale from any maintainer as to why the Common Lisp code is as messy and unidiomatic as it is. It is, by and large, sloppy, difficult to read, and doesn't play well with any existing Common Lisp tooling, difficult to debug, etc. Somebody who finishes reading a textbook like _Practical Common Lisp_ or _Paradigms of AI Programming_ might feel equipped to be a contributor to FriCAS, but then they'll be in for a surprise when they find how goofy and difficult it is to read,

Some people advertise FriCAS as Lisp project.  I do not exactly for
reasons stated above: Lisp programmers may be disappointed.  Part is
what you wrote, part is that FriCAS Lisp code deals with low-level
issues.  Many application programmers consider such issues as crap
best delegated to libraries/implementation.  But the very purpose
of Lisp code in FriCAS is to deal with this crap...

Now, what skills I would find valuable in Lisp programmer?
Ideal person would have experience in low-level high
performance code (like numerics, or some Lisp language
shootout entries).  As bonus knowledge of assemby (or
maybe C).  I would hope that such person would found
ways of speeding up a few of our performance critical
routines.  Such person would write very little code
(or maybe none at all).  Namely critical routines
are written in Spad and preferable improvement would
be via better primitives (currently macros) and
possibly by tweaks of output of Spad compiler.
Main contribution would be knowledge: which coding
patterns leads to faster object code.  In less ideal
word getting speed beyond what is now may require more
substantial changes, possibly separate versions
for each Lisp implementation, maybe calling
external C or assemby routines.  In case of complex
changes there would be uneasy tradeoff between
speed improvements and code complexity.  My current
choices were to limit complexity (at least for
me it is low complexity).  But if somebody was
capable of managing higher complexity code and
commited to maintain it, then more complex code
is a possibilty (given speed benefits).

> for no actually logical reason except for vague appeals to preferred style (e.g., "we like the  Lisp code to look like Boot/Spad code"). What I speculate is the case is that there's no deeply logical reason for the code being the way it is, except that the maintainers are very cognizant of the current structure of the code, and non-trivial changes to the code would be disruptive to the maintainers' mental model and understanding, which would in turn disrupt their ability to maintain.
> 
> Your suggestions to do "differential analysis via git commits" is a testament to the barely tenable nature of the current code; instead of making the code self-evident as to what is implementation-specific or not, we instead have to sift through over 2,000 commits of history to find what people did before if we have any desire to run FriCAS on any of the many extant Lisps (e.g., Allegro, Mezzano, Clasp, SICL, and mocl).

Well, dealing with open source software one has to develop some
skills to survive in unknown environment.  Recently I needed to
compile old gcc version on current system.  Out of the box it
did not work and I had to identify changes needed to make it
buidable.  Looking at changes to gcc with modest effort I was
able to find right patch.  Changes to gcc are huge and "sifting"
trough them is hopeless, but that is not what I suggest.
Simple bisection identified version with fix.  I had resonable
guess (based on error message) about area that may contain fix.
Diff between versions in this area was small enough to that
"sifting" trough it was not a problem (I had also a involved
name which means that basically I had to discard one or two
false positves before I found right place).

So I simply mention this as a method that actually works.

> To be clear, I wholly respect the way the maintainers wish to maintain FriCAS. The maintainers have put in over a decade of effort in keeping this code working, and I'm a newbie who has spent maybe a grand total of one month working with FriCAS source code over the past 10 years. If the FriCAS maintainers tell me, "look, we prefer to make extremely conservative changes because the code is in a working state and our philosophy is to fix bugs and add math functionality," then I'd be OK with that. And, while my PRs have only been up for but a couple days, that is the clear message I am getting. This is my problem for misunderstanding FriCAS's goals as a project (e.g., to make FriCAS [nee Axiom] easier to develop, more efficient, etc.).

Concerning "extremely conservative changes", I am not sure if I agree
with "extremely" but "conservative" is resonable.  Concerning
efficiency, I look at times of various tests (our testsuite is
for correctness and misses important speed aspects), profile
data and generated object code.  In particular macros in 'primitives.lisp'
gave significant speedups.  Beside myself other folks also
contributed valuable speedups.  But there were also cases
when things intended to be a speedup actually were slowdowns.
That happened to myself, there were some proposed changes on
the mailing list.  There were also proposed "code improvements"
that as side effect disabled speed increasing changes.  Bottom
line: I request hard data to justify changes affecting speed
critical parts.  And I have hard data showing speed increases
due to changes.

Concerning easier to develop: IMO FriCAS made significant
progress in ease of developement, but is far from ideal.
Now, please understand that developement in Lisp part is
rather specific: there are speed increasing macros, there
are enhancements/fixes for portability, but very little
algorithmic developement.  If you look at LOC counts in
various languages tendency was decline in LOC of Lisp
and Boot code and increase in Spad.  Lisp probably is
close to minimum now, there are Boot (mostly) and Lisp
(minority) parts that are planned for rewrite or
removal so some Lisp code will go away.  OTOH code in
'src/lisp' are likely to see small growth.  If you
look at diffs you should see that changes in Lisp
parts are rather small.  In "new" Lisp code (that is
written after 2006) we had moderate number of discovered
bugs.  IME, once fault was discoverd it was rather
easy to fix it.  So in a sense code is easy to debug.

Concerning developement: most "new" Lisp developement
was outside FriCAS.  Important part was collecting data,
that is experimentation/reading documentation for
portability parts, benchmarking and disassembly for
speed improvements.  Also analysing profile data to
identify hot spots.  Coding was relatively small part.
So arguments about code editors, debuggers sound
unconvincing to me: they improve easy part, but does
not help in hard one.  Note here I write about debugging
Lisp code present in FriCAS, not Lisp code in general.

Now, when you write about my "ability to maintain": yes
I am concerned.  One aspect is that when something is
puzzling diff with earlier versions frequently gives
valuable hints.  So I prefer to limit reformatting
and similar changes.  More important worry is that
I saw also how quickly code can deteriorate.  Both in
terms of introducing bugs and inefficiences.  So
dont be offended: I want to see that your changes
do not bring regression.  And while in parts that
I looked at I saw no wrong code, I must say that
concerning performance in some places there is
"resonable doubt".  Let me add that you may be very
good programmer but you are new to the project.
I simply do not know what I can expect from you.
So large reformatting changes are not good idea as
first contribution to a project (except if explicitely
asked for such change).  In general (also if you happen
to contribute to some other project) reformatting
should be discussed before going with large changes.
Now, as first contribution reformatting is bad idea
because reviewing burden is as large as for other
changes of similar size, while benefits are presumably
small (because otherwise as an easy change it
would be done earlier).  Just extra remark: when
reformatting is deemed desirable it usually can
be done mechanically.  I can trust that tool
did the right thing without looking at whole
change.  If you do it by hand or do not tell
me how it was done or mix it with other changes,
then in first contribution you put on me burden
that would be not present if I did reformatting
myself.

> I can, at my leisure, always work on a personal copy of FriCAS to make the kinds of changes I feel prudent for improving FriCAS and its ease of use. As a patron of open-source software, however, I wish to put in effort in making my changes available upstream (i.e., to you) so that we don't further contribute to the endless forks of this gargantuan system. I'm trying to offer help as both a user of FriCAS, an interested developer of FriCAS, a professional Common Lisp programmer, and a manager of a team of Common Lisp programmers.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/fricas/fricas/issues/50#issuecomment-795068032

-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
Thanks again for taking the time to comment. It's not something you needed to do, so I appreciate it. I respect your decision on what contributions you seek and how you'd like to maintain your project. Users of FriCAS are certainly appreciative of your efforts.

I think the best course of action is simply for me to work on my own personal copy and not attempt to compartmentalize the changes and upstream them. It is very clearly distracting from this project's goals and priorities. My copy will be available on GitHub, and I'll report to the mailing list any significant interesting functionality or speed-ups I come across, and you and other maintainers may decide to incorporate them as you see fit.
