### ISSUE TITLE
Proposal: Write Boot compiler in Lisp

### ISSUE THREAD

**Issue by stylewarning** [fricas/fricas#52]
I was reading through the Boot code and trying to understand it. According to the Makefile documentation and the source structure, it looks like the Boot compiler is written in Boot, and at some point it bootstrapped itself, and hence there's the `boot/compiled/*` files.

I propose that this initial Boot compiler just remains in Common Lisp so that it can continue to be easily bootstrapped. My specific qualm is that I wanted to fix a bug, namely that the Boot compiler generates

```
(EVAL-WHEN (EVAL LOAD) ...)
```

which ought to be replaced with

```
(EVAL-WHEN (:EXECUTE :LOAD-TOPLEVEL) ...)
```

(This change is one of the many culprits of voluminous and noisy warnings during build.)

To do this, I had to either:

1. manually edit the `compiled/*` code by hand, or
2. rewrite the requisite `.boot` file, figure out how to regenerate the `compiled/*` directory with an existing Boot compiler, then *regenerate it again* to make sure the new bootstrapped changes make it in.

The Makefile documentation suggests Boot is somehow better than Common Lisp because of the syntax. However, I think for specifically the bootstrapping of Boot, Common Lisp would be just fine.

Please note that I am *not* suggesting we replace *all* Boot code with Lisp. I am merely suggesting we port the relatively small amount of functionality as needed in `boot/*`.

**Comment by hebisch** [comment]
On Mon, Mar 08, 2021 at 09:08:30AM -0800, Robert Smith wrote:
> I was reading through the Boot code and trying to understand it. According to the Makefile documentation and the source structure, it looks like the Boot compiler is written in Boot, and at some point it bootstrapped itself, and hence there's the `boot/compiled/*` files.

Yes.

> I propose that this initial Boot compiler just remains in Common Lisp so that it can continue to be easily bootstrapped.

Sorry, no.

> My specific qualm is that I wanted to fix a bug, namely that the Boot compiler generates
> 
> ```
> (EVAL-WHEN (EVAL LOAD) ...)
> ```
> 
> which ought to be replaced with
> 
> ```
> (EVAL-WHEN (:EXECUTE :LOAD-TOPLEVEL) ...)
> ```
> 
> (This change is one of the many culprits of voluminous and noisy warnings during build.)

IIRC when I looked at this several years ago '(:EXECUTE :LOAD-TOPLEVEL)'
caused trouble.  This is probably no longer the case, but would
require some verification that it indeed works in all supported
Lisps (which at still include not so new GCL versions).

> To do this, I had to either:
> 
> 1. manually edit the `compiled/*` code by hand, or
> 2. rewrite the requisite `.boot` file, figure out how to regenerate the `compiled/*` directory with an existing Boot compiler, then *regenerate it again* to make sure the new bootstrapped changes make it in.

That is easy: as long as "old" Boot can compile your change, simply
run make and look at 'src/boot' subdirectory of build tree.
There you will see several files with extension .clisp.  They are
result of Boot to Lisp translation of Boot sources.  In
'src/boot/stage1' subdirectory you will see translations using
"old" Boot compiler, while the ones in 'src/boot' use "new"
compiler.  When you verified that your changes work as intended
simply copy changed .clisp files from build directory to the
'compiled' subdirectory of the source tree.

Note: files in 'compiled' were created by sbcl, to avoid spurious
changes due to differences in Lisp printer new versions also should
be made using sbcl.

Note2: Currently there is difference in whitespace, where version
in 'compiled' has empty lines, generated files contain single
space (use 'diff -bu' to compare ignoring change in amount of
whitespace).

Note3: You can test your changes using ')read' on FriCAS
command line to load new version.  Once interactive test
are OK, do full build.

-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
May I ask, why keep a small number of source files written in Boot just for the sake of being in Boot? Does Boot offer any additional advantages over Lisp for its own compiler implementation?

Advantages I see:

- It's just the way it has always been.

Disadvantages I see:

- Boot files are tracked but are *not* the source of truth. (They only are in principle, but the computer doesn't know that.) As a corollary, source code is duplicated in several different forms.
- Fixing bugs is a lot more error prone due to the multi-step process and needing to reach a fixed point
- Differences in Lisp implementations cause spurious changes to output source code
- Since Boot files need to be compiled to Lisp first, it's not ergonomic to use the interactive development facilities offered by many Lisp environments to develop and improve Boot.

**Comment by hebisch** [comment]
On Mon, Mar 08, 2021 at 02:15:16PM -0800, Robert Smith wrote:
> May I ask, why keep a small number of source files written in Boot just for the sake of being in Boot? Does Boot offer any additional advantages over Lisp for its own compiler implementation?

Yes, Boot has pattern matching constructs that enhance readability.

But I think you miss important part.  You know Lisp, so you prefer
to work with Lisp.  Important advantage of Boot is that its syntax
is almost identical to Spad (with small exception due to pattern
matching which is not present in Spad).  People using FriCAS
will know Spad syntax (because it is what they use as input
to FriCAS).  Most of them do not know Lisp.

In case of Boot compiler, there is another issue: large parts of
Boot compiler are very similar to Spad compiler.  Having both in
the same language make it more easy to keep them in sync (adapt
a bugfix or change affecting interaction between Boot and Spad).

Concernig "small part": currently 'wc' reports me that FriCAS
contains 9562 lines of handwritten Lisp source.  Lisp translation
of Boot compiler is 8603 lines.  Rewriting this by hand you can
make is smaller, but still it would be quite large increase
in Lisp code.  And Boot compiler is algorithmically much
more compilicated than current Lisp code in FriCAS.  So
you propose massive increase of effort spent on Lisp code
in FriCAS.

> Advantages I see:
> 
> - It's just the way it has always been.
> 
> Disadvantages I see:
> 
> - Boot files are tracked but are *not* the source of truth. (They only are in principle, but the computer doesn't know that.) As a corollary, source code is duplicated in several different forms.
That is minor disadvantage.  Note that you have the same problem
for any self-compiling compiler: you need older version to compiler
new one.
> - Fixing bugs is a lot more error prone due to the multi-step process and needing to reach a fixed point
That is really minor issue.  Most bug fixes do not change translation
of Boot files or change it in trivial way.  And sane change will
reach fixpoint after second build, so that is also very minor issue.
Note that _major_ issue is checking that you do not introduce a bug
and fixpoint procedure actually serves as extra test -- so really
bootstrapping gives you benefit of extra test for free.
> - Differences in Lisp implementations cause spurious changes to output source code
Yes.  That is managable, normally we use one main implementation
and when there is need to switch I have a little utility which
compares output ignoring inessential differences (mainly names
of uniterned symbols).
> - Since Boot files need to be compiled to Lisp first, it's not ergonomic to use the interactive development facilities offered by many Lisp environments to develop and improve Boot.
Yes.  However note that main feature of Boot is syntactic similarity
to Spad.  So it really does not change much and most changes were
either bug fixes or few changes to keep syntax in sync with Spad.

Just to explain more about future of FriCAS and Boot: my plan is
that eventually Boot should go away.  Spad compiler should be
rewritten in Spad and bootstrapped in similar way as currently
done for Boot, that is using translated Lisp files from older.
That slow process and most of it is hard to see: files written
in Boot (except for Boot compiler) are cleaned up so that
not only syntax but also semantic matches Spad.  I have small
parts of new Spad compiler in Spad running, but it is not in
repository as ATM is useless for ordinary users.  In principle
I could relativly quickly add few pieces to what I have and
create Boot translator in Spad.  But that would be distraction
from main direction.  Rather, I prefer to keep Boot relatively
stable and let it go away when times comes.

-- 
                              Waldek Hebisch

**Comment by stylewarning** [comment]
Thank you for your thoughtful response. I mostly disagree about the benefits of writing the Boot compiler in Boot, especially since it's a Boot->Lisp compiler, and so I would sure hope that any Boot-compiler hacker is extremely competent at writing Lisp, which unarguably has superior tooling all around than Boot does. As you no doubt know, computer algebra is already hard enough, and I don't find it very sensible to complicate the implementation needlessly, if we are to agree that Lisp will remain the implementation language, the target language, and system's runtime.

With my disagreement in the open, I'm happy to "agree to disagree", and close the issue.

**Comment by ZaquL** [comment]
>Note that you have the same problem
for any self-compiling compiler: you need older version to compiler
new one.

If only it was that simple. There is no way (except Ida Pro checking it all) to garantee that previous versions of gcc (e.g.) did not include some dangerous code to get inserted into all new programs. So in reality you need to somehow compile that previous version of compiler not using even earlier version of it. Also, you **will** have to recompile the compiler again with the same version but generated by older compiler for obvious reasons. Here is how it works for gcc, 16 stages: https://stackoverflow.com/questions/9429491/how-are-gcc-and-g-bootstrapped/65708958#65708958
