### ISSUE TITLE
Use of Unions in SPAD

### ISSUE THREAD

**Issue by portnov** [fricas/fricas#77]
I have a couple of questions about how it is supposed to be...
1. Unions without selectors.
I have a code like
```
myFunc : Union(Integer, String) -> ...
myFunc x ==
    x case Integer => ...
```
and here I want to use `x` knowing that it is actually Integer. If I try to write something like `x + 1`, the compiler complains that it can not perform addition with type `Union(Integer, String)`. The only way I found to convince the compiler that `x` is Integer is `x pretend Integer`. But from my understanding of how `pretend` works, this should not be the preferred way: the compiler does not check that `x` is actually Integer, it just believes me; with same success I could write `x pretend Group`. As far as I understand, `pretend` is an analog of `(type)var` casting from C.
So, the question is: how do I say to compiler, that I have already checked, that `x` is an Integer and not String, without using hacks?

2. Unions with selectors.
This is the continuation of previous. I hoped that probably the answer is to use unions with selectors.

```
myFunc : Union(int : Integer, str : String) -> Integer
myFunc x ==
    x case int  => x.int + 1
    ...
```
Well, this does not cause errors. But how do I construct a value of such type?
```
mkUnion : Integer -> Union(int : Integer, str : String)
mkUnion n = n
```

causes

```
   compiling exported mkUnion : Integer -> Union(int: Integer,str: String)
****** comp fails at level 1 with expression: ******
error in function mkUnion 
(|n|)
****** level 1  ******
$x:= n
$m:= (Union (: int (Integer)) (: str (String)))
$f:=
((((|n| # #) (|mkUnion| #) (|myFunc| #) (|$DomainsInScope| # # #) ...)))
   >> Apparent user error:
   Cannot coerce n 
      of mode (Integer) 
      to mode (Union (: int (Integer)) (: str (String))) 
```

I looked up in "the FriCAS book", but there are no examples of constructing such unions, only an example of usage...

**Comment by hebisch** [comment]
On Tue, Jan 04, 2022 at 08:44:56AM -0800, Ilya V. Portnov wrote:
> I have a couple of questions about how it is supposed to be...
> 1. Unions without selectors.
> I have a code like
> ```
> myFunc : Union(Integer, String) -> ...
> myFunc x ==
>     x case Integer => ...
> ```
> and here I want to use `x` knowing that it is actually Integer. If I try to write something like `x + 1`, the compiler complains that it can not perform addition with type `Union(Integer, String)`. The only way I found to convince the compiler that `x` is Integer is `x pretend Integer`. But from my understanding of how `pretend` works, this should not be the preferred way: the compiler does not check that `x` is actually Integer, it just believes me; with same success I could write `x pretend Group`. As far as I understand, `pretend` is an analog of `(type)var` casting from C.
> So, the question is: how do I say to compiler, that I have already checked, that `x` is an Integer and not String, without using hacks?

Basically, compiler will do right thing if at right place (time)
it knows that expression needs Integer instead of Union.  But
currently compiler may miss fact that Integer is needed
and later may be too late to fix this.

Normally the following should work:

     u case Integer =>
         i : Integer := u
         -- use i as needed in the following

If value is used only once, then you may try ***@***.***'.  'pretend'
is dangerous, basically it works only because '@' works.  More
precisely, using unions involves compiler generated code to
change representation (strip tags).  'pretend' alone does not
generate such code.  The only good thing that 'pretend' is
doing in your example is telling compiler that you want
Integer.

> 2. Unions with selectors.
> This is the continuation of previous. I hoped that probably the answer is to use unions with selectors.
> 
> ```
> myFunc : Union(int : Integer, str : String) -> Integer
> myFunc x ==
>     x case int  => x.int + 1
>     ...
> ```
> Well, this does not cause errors. But how do I construct a value of such type?

AFAIK there is no way in Spad.
> ```
> mkUnion : Integer -> Union(int : Integer, str : String)
> mkUnion n = n
> ```
> 
> causes
> 
> ```
>    compiling exported mkUnion : Integer -> Union(int: Integer,str: String)
> ****** comp fails at level 1 with expression: ******
> error in function mkUnion 
> (|n|)
> ****** level 1  ******
> $x:= n
> $m:= (Union (: int (Integer)) (: str (String)))
> $f:=
> ((((|n| # #) (|mkUnion| #) (|myFunc| #) (|$DomainsInScope| # # #) ...)))
>    >> Apparent user error:
>    Cannot coerce n 
>       of mode (Integer) 
>       to mode (Union (: int (Integer)) (: str (String))) 
> ```
> 
> I looked up in "the FriCAS book", but there are no examples of constructing such unions, only an example of usage...

Well, there is example, but is in "interpeter language":

u : Union(int: Integer,str: String)
u := "good morning"

In principle implementing the above in Spad is not very hard.
However, it is not clear it Spad should support this.  More
precisely, main advantage of tags is that you can have
types like

Union(int : Integer, str : Integer)

that is types corresponing to different tags are the same.
But currently with

u : Union(int : Integer, str : Integer)
u := 42

in interpreter you silently get 'int' branch.  This may be
tolerable in interactive use, because in interactive context
errors tend to show up quickly.  But Spad is supposed to be
safe and making choice like above may easily hide an error.

-- 
                              Waldek Hebisch

**Comment by billpage** [comment]
I was a little confused by Waldek's answer but perhaps the following
example will help.

In the interpreter:

(1) -> myFunc : Union(Integer, String) -> Integer

                                                                   Type:
Void
(2) -> myFunc x == (if x case Integer then x::Integer+1 else
parse_integer(x::String)$ScanningUtilities+1)
                                                                   Type:
Void
(3) -> myFunc 3

   Compiling function myFunc with type Union(Integer,String) -> Integer

   (3)  4
                                                        Type:
PositiveInteger
(4) -> myFunc "3"

   (4)  4
                                                        Type:
PositiveInteger
(5) -> myFunc2 : Union(int:Integer, str:String) -> Integer

                                                                   Type:
Void
(6) -> myFunc2 x == (if x case int then x.int+1 else
parse_integer(x.str)$ScanningUtilities+1)
                                                                   Type:
Void
(7) -> myFunc2 3

   Compiling function myFunc2 with type Union(int: Integer,str: String) ->
Integer

   (7)  4
                                                        Type:
PositiveInteger
(8) -> myFunc "3"


   (8)  4
                                                        Type:
PositiveInteger

(9) -> mkUnion : Integer -> Union(int : Integer, str : String)
                                                                   Type:
Void
(10) -> mkUnion n == [n]
                                                                   Type:
Void
(11) -> mkUnion 3
   Compiling function mkUnion with type Integer -> Union(int: Integer, str:
String)

   (11)  3
                                                Type: Union(int:
Integer,...)
(12) -> myFunc %

   (12)  4
                                                        Type:
PositiveInteger

In SPAD:
-- file: test-myfunc.spad
)abbrev package TEST1 TestMyFunc
TestMyFunc() : Exports == Implementation where
  Exports ==> with
    myFunc:Union(Integer,String) -> Integer
    myFunc2 : Union(int:Integer, str:String) -> Integer
    mkUnion : Integer -> Union(int : Integer, str : String)

  Implementation ==> add
    myFunc x ==
      if x case Integer then
        x::Integer+1
      else
        parse_integer(x::String)$ScanningUtilities+1

    myFunc2 x ==
      if x case int then
        x.int+1
      else
        parse_integer(x.str)$ScanningUtilities+1

    mkUnion n == [n]
--
(1) -> )co test-myfunc.spad
...
(1) -> mkUnion 3

   (1)  3
                                                Type: Union(int:
Integer,...)
(2) -> myFunc2 %

   (2)  4
                                                        Type:
PositiveInteger

Regards,
Bill Page.

**Comment by hebisch** [comment]
On Mon, Jan 10, 2022 at 09:22:16AM -0800, Bill Page wrote:
> I was a little confused by Waldek's answer but perhaps the following
> example will help.
> 
> In the interpreter:
> 
> (1) -> myFunc : Union(Integer, String) -> Integer
> 
>                                                                    Type:
> Void
> (2) -> myFunc x == (if x case Integer then x::Integer+1 else
> parse_integer(x::String)$ScanningUtilities+1)
>                                                                    Type:
> Void
> (3) -> myFunc 3
> 
>    Compiling function myFunc with type Union(Integer,String) -> Integer
> 
>    (3)  4
>                                                         Type:
> PositiveInteger
> (4) -> myFunc "3"
> 
>    (4)  4

Ilya asked about Spad.  In Spad one can write:

    myFunc(x : Union(Integer, String)) : Integer ==
        x case Integer => ***@***.*** + 1
        ***@***.***)$ScanningUtilities+1

Note: The above uses AT sign.  If you view this via web
interface it is likely that code surrounding AT sign will
be mangled.  Using AT sign as above does not work in
interpreter (interpreter is not smart enough to see that
earlier there was check for correct branch).  In some cases
Spad compiler may get confused and do not realize that code
checked for correct branch.  In such case AT will cause error
message and one have to use '::'.  However, AT works when
'pretend' would generate correct code.  When compiler rejects
AT using 'pretend' would give wrong code.  So never use 'pretend'
when you have a union and want a branch.

Currently FriCAS algebra code uses '::' quite a lot.  But
it is better to use AT because of stricter checking.  Use
'::' only when compiler is confused and do not understand
that you checked for correct branch.  Note: in such cases
'::' will generate (extra) runtime check for correct
branch, so if union have different branch, then there
will be error at runtime.  Using AT there is no possibilty
for runtime error.

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
On Tue, Jan 04, 2022 at 08:44:56AM -0800, Ilya V. Portnov wrote:
> 2. Unions with selectors.
> This is the continuation of previous. I hoped that probably the answer is to use unions with selectors.
> 
> ```
> myFunc : Union(int : Integer, str : String) -> Integer
> myFunc x ==
>     x case int  => x.int + 1
>     ...
> ```
> Well, this does not cause errors. But how do I construct a value of such type?
> ```
> mkUnion : Integer -> Union(int : Integer, str : String)
> mkUnion n = n
> ```
> 
> causes
> 
> ```
>    compiling exported mkUnion : Integer -> Union(int: Integer,str: String)
> ****** comp fails at level 1 with expression: ******
> error in function mkUnion 
> (|n|)
> ****** level 1  ******
> $x:= n
> $m:= (Union (: int (Integer)) (: str (String)))
> $f:=
> ((((|n| # #) (|mkUnion| #) (|myFunc| #) (|$DomainsInScope| # # #) ...)))
>    >> Apparent user error:
>    Cannot coerce n 
>       of mode (Integer) 
>       to mode (Union (: int (Integer)) (: str (String))) 
> ```
> 
> I looked up in "the FriCAS book", but there are no examples of constructing such unions, only an example of usage...

A little correction to my previous answer.  I overlooked important
function: 'construct' (usually written as square brackets).  Using
it one can write:

)abbrev package TU TestUnion
TestUnion() : Exports == Implementation where
  U ==> Union(int : Integer, str : Integer)
  Exports ==> with
    mkUnion : Integer -> U
  Implementation ==> add

    mkUnion n == [n]

where mkUnion constructs union with selector.

-- 
                              Waldek Hebisch

**Comment by hebisch** [comment]
Now one can select branch by giving tag in constructor like [int == 42].  That
should solve possible confusion,
